### ISSUE TITLE
[refactor] Use a configuration manager

### ISSUE THREAD

**Issue by geeneve** [TeamBookTez/booktez-server#132]
## 🧐 Refactoring Target
- 모든 보안 정보가 필요한 부분에서 `process.env`로 호출하지 않고 configuration manager 파일을 만들어 불러오도록 리팩토링

## 📝 To Do

- [ ] `src/config/index.ts` 추가
- [ ] 현재 `process.env` 사용 중인 코드 수정

## ✅ Issue check list

1. Assignees, Labels 확인하기
2. Milestone 연결 확인하기

**Comment by holmir97** [comment]
bbb
