### ISSUE TITLE
[fix] Build JS in EC2 instance

### ISSUE THREAD

**Issue by geeneve** [TeamBookTez/booktez-server#134]
## 🐞 Change
- 현재 메모리 초과등의 사유로 로컬에서 TS->JS 컴파일 후 github를 이용해 배포하는 방식 사용 중
- EC2 인스턴스 내에서 자동 빌드 & 배포 할 수 있도록 해결 방법 찾아보기

## 📝 To Do

- [x] 해결법 찾아서 적용!

## ✅ Issue check list

1. Assignees, Labels 확인하기
2. Milestone 연결 확인하기

**Comment by holmir97** [comment]
dist 이게 문젭니다.. 로그를 보면 메모리 용량 에러라고 나오지만 더 컴팩트하게 배포할 수 있는 방법을 찾아봐야 할 것 같습니다.

**Comment by geeneve** [comment]
`220429`
2시간의 연구 결과 돈이 해결해주는 것으로..... 판명되었습니다.
